# Generated by Django 3.2.9 on 2021-11-11 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 11, 19, 21, 798068, tzinfo=utc), verbose_name='buy date'),
        ),
    ]
