# Generated by Django 3.2.9 on 2021-11-11 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_alter_item_buy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='buy date'),
        ),
    ]
