# Generated by Django 3.2.9 on 2021-11-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_content_github_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('github_link', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(choices=[('EDU', 'Education'), ('WORK', 'Work Experience')], default='WORK', max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('responsibility', models.TextField(default='')),
                ('projects', models.TextField(default='')),
                ('technologies', models.TextField(default='')),
                ('reference', models.TextField(default='')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
            preserve_default=False,
        ),
    ]
