# Generated by Django 3.2.9 on 2021-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211118_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='responsibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='technologies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
