# Generated by Django 3.2.9 on 2021-11-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211118_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='github_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
