# Generated by Django 3.2.9 on 2021-11-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211119_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
