# Generated by Django 3.2.9 on 2021-11-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_content_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
