# Generated by Django 3.2.9 on 2021-11-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_content_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
